name: Get full info

on:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    uses: symbioticfi/metadata-validation-scripts/.github/workflows/full-info.yml@main
